// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationService.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationService.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RecipientContact")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Subject")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId", "CreatedAt")
                        .HasFilter("\"RecipientUserId\" IS NOT NULL");

                    b.ToTable("notification_logs", (string)null);
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code", "Channel")
                        .IsUnique();

                    b.ToTable("notification_templates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            Body = "Здравствуйте!\n\nВаша заявка {{OrderNumber}} на перевозку из города {{OriginCity}} в город {{DestinationCity}} создана.\nМы сообщим, когда она будет подтверждена.",
                            Channel = "Email",
                            Code = "OrderCreated",
                            Subject = "Заявка {{OrderNumber}} создана"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            Body = "Заявка {{OrderNumber}} подтверждена.\n\nСтоимость перевозки — {{CalculatedPrice}} руб.\nЖелаемый срок доставки — {{DeliveryDeadline}}.",
                            Channel = "Email",
                            Code = "OrderConfirmed",
                            Subject = "Заявка {{OrderNumber}} подтверждена"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            Body = "Заявка {{OrderNumber}} отменена.\n\nПричина: {{Reason}}",
                            Channel = "Email",
                            Code = "OrderCancelled",
                            Subject = "Заявка {{OrderNumber}} отменена"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            Body = "Груз принят на склад.\n\nТрек-номер для отслеживания — {{TrackingNumber}}.\nСостояние упаковки при приёмке: {{PackagingCondition}}.\nСостояние груза: {{CargoCondition}}.",
                            Channel = "Email",
                            Code = "CargoAccepted",
                            Subject = "Груз принят на склад, трек-номер {{TrackingNumber}}"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            Body = "Статус груза {{TrackingNumber}} изменился на «{{Status}}».\n\nМестоположение: {{Location}}.",
                            Channel = "Email",
                            Code = "CargoStatusChanged",
                            Subject = "Груз {{TrackingNumber}}: статус «{{Status}}»"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000006"),
                            Body = "Груз {{TrackingNumber}} выдан получателю {{ReceivedByName}}.\n\nСпасибо, что выбрали нас.",
                            Channel = "Email",
                            Code = "CargoDelivered",
                            Subject = "Груз {{TrackingNumber}} выдан"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000007"),
                            Body = "Оплата на сумму {{Amount}} руб. получена.\n\nСпасибо!",
                            Channel = "Email",
                            Code = "PaymentCompleted",
                            Subject = "Оплата получена"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000008"),
                            Body = "Оплату по заявке провести не удалось.\n\nПричина: {{Reason}}.\nПовторите оплату в личном кабинете.",
                            Channel = "Email",
                            Code = "PaymentFailed",
                            Subject = "Оплата не прошла"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000009"),
                            Body = "По вашей заявке подготовлен документ: {{DocumentType}}.\n\nОн доступен в личном кабинете.",
                            Channel = "Email",
                            Code = "DocumentGenerated",
                            Subject = "Документ «{{DocumentType}}» готов"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000010"),
                            Body = "Автоматическая проверка фото разошлась с оценкой сотрудника.\n\nГруз: {{ShipmentId}}.\nПовреждение по мнению модели: {{DamageDetected}} (уверенность {{Confidence}}).\nПроверка: {{InspectionJobId}}.\n\nТребуется перепроверка груза сотрудником склада.",
                            Channel = "Email",
                            Code = "PackageIntegrityAssessed",
                            Subject = "Расхождение оценки упаковки по грузу {{ShipmentId}}"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            Body = "Груз {{TrackingNumber}}: {{Status}}.",
                            Channel = "Sms",
                            Code = "CargoStatusChanged"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            Body = "Груз {{TrackingNumber}} выдан. Спасибо, что выбрали нас.",
                            Channel = "Sms",
                            Code = "CargoDelivered"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            Body = "Оплата по заявке не прошла. Повторите оплату в личном кабинете.",
                            Channel = "Sms",
                            Code = "PaymentFailed"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
